services:
  tonearm:
    image: ghcr.io/renaud11232/tonearm
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "your discord token"
      YOUTUBE_API_KEY: "your youtube api key"
    volumes:
      - /opt/tonearm/tonearm:/data
