from .clean import CleanCommand
from .clear import ClearCommand
from .debug import DebugCommand
from .dj import DjCommand
from .forward import ForwardCommand
from .join import JoinCommand
from .jump import JumpCommand
from .leave import LeaveCommand
from .loop import LoopCommand
from .move import MoveCommand
from .next import NextCommand
from .now import NowCommand
from .pause import PauseCommand
from .play import PlayCommand
from .previous import PreviousCommand
from .queue import QueueCommand
from .remove import RemoveCommand
from .resume import ResumeCommand
from .rewind import RewindCommand
from .seek import SeekCommand
from .setting import SettingCommand
from .shuffle import ShuffleCommand
from .shutdown import ShutdownCommand
from .stop import StopCommand
from .version import VersionCommand
from .voteskip import VoteskipCommand