name: Docker

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install "hatchling >= 1.27" "hatch-vcs >= 0.5.0"
      - id: version
        run: hatchling version | tee -a $GITHUB_OUTPUT
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: |
            ghcr.io/Renaud11232/tonearm
          tags: |
            type=pep440,pattern={{version}},value=v${{ steps.version.outputs.version }}
            type=pep440,pattern={{major}}.{{minor}},value=v${{ steps.version.outputs.version }}
            type=pep440,pattern={{major}},value=v${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.title=tonearm
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64